name: 🐛 Bug Report
description: File a bug report to help us improve KairOS
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Tap NFC card or use simulator
        3. Enter PIN '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome (Android)
        - Chrome (Desktop)
        - Edge (Android)
        - Edge (Desktop)
        - Safari (iOS)
        - Safari (Desktop)
        - Firefox
        - Other
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device?
      options:
        - Android Phone
        - iPhone
        - Desktop/Laptop
        - Tablet
        - Other
    validations:
      required: true

  - type: checkboxes
    id: nfc-availability
    attributes:
      label: NFC Testing
      description: How did you test this?
      options:
        - label: I have an NFC-capable device
        - label: I'm using the simulator
        - label: This issue occurs with real NFC cards
        - label: This issue occurs in simulation mode

  - type: dropdown
    id: authentication-stage
    attributes:
      label: Authentication Stage
      description: At what stage does the issue occur?
      options:
        - label: NFC card reading
        - label: PIN entry
        - label: Key derivation
        - label: Profile access
        - label: Way of Flowers installation
        - label: Other/Not applicable
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. Include screenshots if helpful.
        
        **Console Errors**: If you see any errors in the browser console (F12), please include them.
        **Network Tab**: Any failed network requests in the browser dev tools. 