name: 📚 Documentation
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation", "good first issue"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Clear docs make KairOS more accessible to everyone.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README
        - Getting Started Guide
        - API Documentation
        - Architecture Guide
        - Contributing Guide
        - Installation Framework
        - Code Comments
        - Error Messages
        - Other
    validations:
      required: true

  - type: textarea
    id: current-problem
    attributes:
      label: Current Problem
      description: What's unclear, missing, or incorrect in the current documentation?
      placeholder: The current documentation says... but I expected...
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: How should the documentation be improved?
      placeholder: The documentation should explain...

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      options:
        - New Contributors
        - End Users
        - Developers
        - Researchers
        - Installation Creators
        - Security Auditors
        - All Users
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I can help write this documentation
        - label: I can provide examples or use cases
        - label: I can review the improved documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Links to relevant sections, examples from other projects, or any other helpful context. 